<?php
    $slack_hook = "";

    $debug = false;

    $nouns = array("chapter", "message", "data", "week", "phone", "height", "equipment", "newspaper", "entry", "consequence",
        "shopping", "performance", "knowledge", "growth", "apartment", "lab", "hair", "insurance", "republic", "reception",
        "temperature", "resource", "understanding", "addition", "decision", "maintenance", "writer", "poetry", "pie", "song",
        "drawer", "competition", "basis", "improvement", "departure", "presence", "literature");

    $adjectives = array("organic", "panoramic", "majestic", "furtive", "decisive", "cool", "broad", "green", "typical",
        "blue", "red", "yellow", "purple", "magenta", "smiling", "smart", "entire", "knowledgeable", "amused", "interesting",
        "curious", "nice", "zesty", "detailed", "grey", "gifted", "coordinated");

    session_start();
